name = "bansuri-api"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
ADMIN_EMAIL = "bansuricatering@gmail.com"
ADMIN_PASSWORD = "123456"

[[d1_databases]]
binding = "DB"
database_name = "bansuri-db"
database_id = "315a68fa-db5c-4b06-a6f3-1ab19ff7253e"
